---
- hosts: all
  become: true
  # vars:
  #   create_containers: 1
  #   default_container_name: httpd
  #   default_container_image:
  #   default_container_command:

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes


    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: create website folder
      file:
        path: /root/webSite
        state: directory

    - name: copy docker.html
      copy:
        src: "docker.html"
        dest: "/root/webSite/"
      ignore_errors: yes


    # Pull image specified by variable default_image from the Docker Hub
    # - name: Pull default Docker image
    #   docker_image:
    #     name: "{{ default_container_image }}"
    #     source: pull

    - name: Pull default Docker image
      docker_image:
        name: httpd
        source: pull

    - name: Creating Docker Container
      docker_container:
        name: myContainer
        image: httpd
        state: started
        detach: true
        interactive: true
        ports:
        - "8030:80"
        volumes:
        - /root/webSite/:/usr/local/apache2/htdocs/

    # # Creates the number of containers defined by the variable create_containers, using default values
    # - name: Create default containers
    #   docker_container:
    #     name: "{{ default_container_name }}{{ item }}"
    #     image: "{{ default_container_image }}"
    #     command: "{{ default_container_command }}"
    #     state: present
    #   with_sequence: count={{ create_containers }}
